Cora:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 50
  weight_decay: 0.00001
  _lambda: 10
CiteSeer:
  seed: 38108
  learning_rate: 0.0005
  num_hidden: 2048
  num_proj_hidden: 2048
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  num_epochs: 30
  weight_decay: 0.00001
  _lambda: 1
PubMed:
  seed: 23344
  learning_rate: 0.0005
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 200
  weight_decay: 0.00001
  _lambda: 0.1
DBLP:
  seed: 83521
  learning_rate: 0.0005
  num_hidden: 600
  num_proj_hidden: 600
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.0
  tau: 0.7
  num_epochs: 1000
  weight_decay: 0.00001
  _lambda: 1
WikiCS:
  seed: 83521
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  tau: 0.4
  num_epochs: 300
  weight_decay: 0.00001
  _lambda: 0.1
Amazon-Computers:
  seed: 83521
  learning_rate: 0.001
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'rrelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.6
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.2
  num_epochs: 400
  weight_decay: 0.00001
  _lambda: 5
Amazon-Photo:
  seed: 83521
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 64
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  tau: 0.3
  num_epochs: 400
  weight_decay: 0.00001
  _lambda: 1
Coauthor-CS:
  seed: 83521
  learning_rate: 0.0001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'rrelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 300
  weight_decay: 0.00001
  _lambda: 1
Coauthor-Phy:
  seed: 83521
  learning_rate: 0.0005
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'rrelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.4
  tau: 0.3
  num_epochs: 100
  weight_decay: 0.00001
  _lambda: 10
ogbn-arxiv:
  seed: 83521
  learning_rate: 0.0005
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 3
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 0.4
  num_epochs: 1000
  weight_decay: 0.00001
  _lambda: 10